language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
env:
  matrix:
    - "TASK=test"
    - "TASK=bench"
script: "bundle exec rake $TASK"
